# Generated by Django 4.0.6 on 2024-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalOnline', '0003_remove_article_author_alter_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Politics'), (2, 'Science'), (3, 'Culture'), (4, 'Entertainment'), (5, 'Sports'), (6, 'Technology'), (7, 'Health'), (8, 'Business'), (9, 'Environment'), (10, 'World')], default=1),
        ),
    ]
