# Generated by Django 4.0.6 on 2024-05-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectImage', models.ImageField(blank=True, upload_to='projeto/projectImage/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtubeVideo', models.URLField(blank=True, max_length=300)),
                ('gitHub', models.URLField(blank=True, max_length=300)),
                ('conceitosAplicados', models.ManyToManyField(blank=True, related_name='ProjectConcepts', to='portfolio.concepts')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('linkedinLink', models.URLField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('apresentacao', models.TextField(blank=True)),
                ('curricularIUnitReadableCode', models.CharField(blank=True, max_length=300)),
                ('ects', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1)),
                ('nota', models.IntegerField(default=0)),
                ('programa', models.ManyToManyField(related_name='Programa', to='portfolio.concepts')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('scientificArea', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.scientificarea')),
                ('teacher', models.ManyToManyField(related_name='SubjectTeacher', to='portfolio.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('apresentation', models.TextField(blank=True)),
                ('courseType', models.IntegerField(choices=[(1, "Bachelor's Degree"), (2, "Master's Degree"), (3, 'PhD')], default=1)),
                ('subjects', models.ManyToManyField(related_name='course_subjects', to='portfolio.subject')),
            ],
        ),
    ]
