# Generated by Django 4.0.6 on 2024-05-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='conceitosAplicados',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='programa',
        ),
        migrations.DeleteModel(
            name='Concepts',
        ),
    ]
