# Generated by Django 4.0.6 on 2024-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='project',
            name='conceitosAplicados',
            field=models.ManyToManyField(blank=True, related_name='ProjectConcepts', to='portfolio.concept'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
