# Generated by Django 4.0.6 on 2024-05-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_course_subjects_project_conceitosaplicados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('apresentacao', models.TextField(blank=True)),
                ('curricularIUnitReadableCode', models.CharField(blank=True, max_length=300)),
                ('ects', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1)),
                ('nota', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.course')),
                ('programa', models.ManyToManyField(related_name='Programa', to='portfolio.concept')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('scientificArea', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.scientificarea')),
                ('teacher', models.ManyToManyField(related_name='SubjectTeacher', to='portfolio.teacher')),
            ],
        ),
    ]
