# Generated by Django 4.0.6 on 2024-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='conceitosAplicados',
            field=models.ManyToManyField(blank=True, related_name='CourseConcepts', to='portfolio.concept'),
        ),
    ]
