# Generated by Django 4.0.6 on 2024-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_scientificarea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
