# Generated by Django 4.0.6 on 2024-07-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0004_delete_album_delete_band_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50)),
                ('start_date', models.IntegerField()),
                ('music_type', models.IntegerField(choices=[(1, 'Rock'), (2, 'Metal'), (3, 'Pop'), (4, 'Blues'), (5, 'Jazz'), (6, 'Folk'), (7, 'Rap')], default=1)),
                ('band_image', models.ImageField(blank=True, upload_to='bands/')),
            ],
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.IntegerField(verbose_name='Birth Date')),
                ('musician_image', models.ImageField(blank=True, upload_to='musicians/')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bands.band')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=50)),
                ('release_date', models.IntegerField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='bands.bandmember')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('album_release_date', models.IntegerField(blank=True)),
                ('album_image', models.ImageField(blank=True, upload_to='albums/')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='bands.band')),
                ('musics', models.ManyToManyField(related_name='albums', to='bands.music')),
            ],
        ),
    ]
