# Generated by Django 4.0.6 on 2024-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
