# Generated by Django 4.0.6 on 2024-07-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_bandmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='role',
        ),
    ]
