# Generated by Django 4.0.6 on 2024-07-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_remove_bandmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='bands.bandmember'),
        ),
    ]
