# Generated by Django 4.0.6 on 2024-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_alter_music_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
    ]
